*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSA05VEN.......................................*
FORM GET_DATA_ZVSA05VEN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSA05VEN WHERE
(VIM_WHERETAB) .
    CLEAR ZVSA05VEN .
ZVSA05VEN-MANDT =
ZTSA05VEN-MANDT .
ZVSA05VEN-LIFNR =
ZTSA05VEN-LIFNR .
ZVSA05VEN-LAND1 =
ZTSA05VEN-LAND1 .
ZVSA05VEN-NAME1 =
ZTSA05VEN-NAME1 .
ZVSA05VEN-NAME2 =
ZTSA05VEN-NAME2 .
ZVSA05VEN-VENCA =
ZTSA05VEN-VENCA .
ZVSA05VEN-CARRID =
ZTSA05VEN-CARRID .
ZVSA05VEN-MEALNO =
ZTSA05VEN-MEALNO .
ZVSA05VEN-PRICE =
ZTSA05VEN-PRICE .
ZVSA05VEN-WAERS =
ZTSA05VEN-WAERS .
<VIM_TOTAL_STRUC> = ZVSA05VEN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSA05VEN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSA05VEN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSA05VEN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSA05VEN WHERE
  LIFNR = ZVSA05VEN-LIFNR .
    IF SY-SUBRC = 0.
    DELETE ZTSA05VEN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSA05VEN WHERE
  LIFNR = ZVSA05VEN-LIFNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSA05VEN.
    ENDIF.
ZTSA05VEN-MANDT =
ZVSA05VEN-MANDT .
ZTSA05VEN-LIFNR =
ZVSA05VEN-LIFNR .
ZTSA05VEN-LAND1 =
ZVSA05VEN-LAND1 .
ZTSA05VEN-NAME1 =
ZVSA05VEN-NAME1 .
ZTSA05VEN-NAME2 =
ZVSA05VEN-NAME2 .
ZTSA05VEN-VENCA =
ZVSA05VEN-VENCA .
ZTSA05VEN-CARRID =
ZVSA05VEN-CARRID .
ZTSA05VEN-MEALNO =
ZVSA05VEN-MEALNO .
ZTSA05VEN-PRICE =
ZVSA05VEN-PRICE .
ZTSA05VEN-WAERS =
ZVSA05VEN-WAERS .
    IF SY-SUBRC = 0.
    UPDATE ZTSA05VEN ##WARN_OK.
    ELSE.
    INSERT ZTSA05VEN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSA05VEN-UPD_FLAG,
STATUS_ZVSA05VEN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVSA05VEN.
  SELECT SINGLE * FROM ZTSA05VEN WHERE
LIFNR = ZVSA05VEN-LIFNR .
ZVSA05VEN-MANDT =
ZTSA05VEN-MANDT .
ZVSA05VEN-LIFNR =
ZTSA05VEN-LIFNR .
ZVSA05VEN-LAND1 =
ZTSA05VEN-LAND1 .
ZVSA05VEN-NAME1 =
ZTSA05VEN-NAME1 .
ZVSA05VEN-NAME2 =
ZTSA05VEN-NAME2 .
ZVSA05VEN-VENCA =
ZTSA05VEN-VENCA .
ZVSA05VEN-CARRID =
ZTSA05VEN-CARRID .
ZVSA05VEN-MEALNO =
ZTSA05VEN-MEALNO .
ZVSA05VEN-PRICE =
ZTSA05VEN-PRICE .
ZVSA05VEN-WAERS =
ZTSA05VEN-WAERS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSA05VEN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSA05VEN-LIFNR TO
ZTSA05VEN-LIFNR .
MOVE ZVSA05VEN-MANDT TO
ZTSA05VEN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSA05VEN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSA05VEN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSA05VEN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
